name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@c5ba7f7862a0f64c1b1a05fbac13e0b8e86ba08c # v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.2.0
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile
        run: pnpm compile

      - name: Package VSIX
        run: pnpm package:vsix

      - name: Get VSIX file name
        id: get_vsix
        run: |
          VSIX_FILE=$(ls dist/*.vsix)
          echo "VSIX_PATH=$VSIX_FILE" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: ${{ env.VSIX_PATH }}
          generate_release_notes: true
